### ISSUE TITLE
CustomNPC integration required!

### ISSUE THREAD

**Issue by Magi1053** [JimiIT92/UniverseGuard#11]
https://minecraft.curseforge.com/projects/custom-npcs
I have Custom NPC's at my spawn. If I define a region around the spawn and set the flag 'mobs' to false, I cannot place NPC, and already placed NPC's will not load when the server restarts!

**Comment by JimiIT92** [comment]
That's actually correct since custom npc's entities are seen by sponge as mobs. But fortunately i'm working on a rework of that flag so you can specifiy wich specific mobs can/can't spawn ;)
