### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by bombaroberta** [JimiIT92/UniverseGuard#12]
Universguard crashes the server regularly. Since i deleted it, my server work normally but i need it for the flag region. Is there a way to stop the crashing or a new release which fix it ?

**Comment by JimiIT92** [comment]
A new version will come soon, but i recommend to post the crash log to see what's causing it so it will be fixed for the next release

**Comment by bombaroberta** [comment]
I use nation and universguard and since I removed universguard the server did not crash however I need universguard for have flag and region but he crash my server. We get 2 type of crash reports: 
- https://gist.github.com/bombaroberta/bba7ccde5d38206df72840852ef21a23
