### ISSUE TITLE
Max regions 

### ISSUE THREAD

**Issue by astetyn** [JimiIT92/UniverseGuard#17]
Hello,

I didnt find anything like "max regions" for specific permission group. Is there any posibility to set the max value of created regions by some player? Thanks.

**Comment by JimiIT92** [comment]
Right now you can't set a different limit based on permission, but i can change that so each permission will have it's own limit ;)

**Comment by astetyn** [comment]
That would be amazing. And is there now any global option for the limit of regions?

**Comment by JimiIT92** [comment]
Didn't noticed this was posted on the old repository. The max regions global setting is available by the way and is in the latest universe guard 2 release, wich can be found [here](https://forums.spongepowered.org/t/universe-guard-2-an-easy-to-use-world-protection-plugin/21661/158)
