### ISSUE TITLE
[1.12.2] Could not pass MoveEntityEvent

### ISSUE THREAD

**Issue by Rsslone** [JimiIT92/UniverseGuard#18]
[Server] Server thread/ERROR [Sponge]: Could not pass MoveEntityEvent$Impl to Plugin{id=universeguard, name=Universe Guard 2, version=2.14, description=An easy to use world protection plugin for Sponge, authors=[JimiIT92, Brycey92, eheimer], source=/./mods/plugins/UniverseGuard-2.14-1.12.2.jar}

API VERSION: 7.1.0-SNAPSHOT-43d8496
Sponge VERSION: 1.12.2-2705-7.1.0-BETA-3136

**Comment by JimiIT92** [comment]
Moved here [https://github.com/JimiIT92/UniverseGuard2/issues/49](https://github.com/JimiIT92/UniverseGuard2/issues/49)

Will look into this as soon as possible
