### ISSUE TITLE
Global Flags Bug

### ISSUE THREAD

**Issue by SerendipityMC** [JimiIT92/UniverseGuard#2]
Setting global flags sometimes causes the entirely incorrect flag (or multiple flags) to change.

Example:
I see that drown is set to false, I use `/region global drown true` and then I look again at the flags with `/region globallist` and instead of drowning being enabled, walldamage was disabled.

If I try again, with the same command, walldamage is enabled and instead enderchests is disabled.

Drowning however, never changes.

**Comment by JimiIT92** [comment]
Thank you for the report. This is now fixed and a new version will be posted on the Sponge forum soon
