### ISSUE TITLE
rentable region

### ISSUE THREAD

**Issue by Nbgreen** [JimiIT92/UniverseGuard#21]
Hi, I was wondering if you could make it where users can rent out a region (like /rg rent) for a set amount of money for a set amont of time instead of just strait out buying it. The reason I ask for this is because I'm trying to make rentable regions for player shop on my server and I cant find any plugins that offer that if you would consider doing it would be much appreciated.

**Comment by JimiIT92** [comment]
There are actually plans to separate that part from the main plugin and make it as an addon. I will add this feature into that addon ;)

**Comment by Nbgreen** [comment]
I paid a guy to make an addon for your plugin to do this
