### ISSUE TITLE
Use Ore or Github Releases for Downloading

### ISSUE THREAD

**Issue by SerendipityMC** [JimiIT92/UniverseGuard#3]
On the Sponge page, MEGA and MediaFire links are used for downloading.

Please consider using Sponge's [Ore](https://ore.spongepowered.org/) system, and/or Github's release system for publishing new versions, with the inclusion of proper versioning and changelogs.

**Comment by JimiIT92** [comment]
Added the project the to Sponge's Ore system. You can find it here
https://ore.spongepowered.org/Francesco_Jimi/Universe-Guard

**Comment by SerendipityMC** [comment]
The downloads do not work (you may have used Ore incorrectly).

Please review [the documentation](https://docs.spongepowered.org/stable/en/ore/publish.html)
