### ISSUE TITLE
[1.0.4] formatting issue of displayed text when running /region list

### ISSUE THREAD

**Issue by bhi-elliot** [JimiIT92/UniverseGuard#6]
Hi there,

When there are multiple regions and a player runs:
`/region list`

The formatting of the text is wrong I believe. I has multiple lines, for eample:

> -----------Region list-------------
> -----------Region list-------------
> -----------Region list-------------
> -----------Region list-------------
> region1, region2, region3, region4,

Like that. It prints the heading for however many regions that are made, and there is an extra comma at the end. Not a big issue, just a graphic one.

Hope that helps.
Thanks!

**Comment by JimiIT92** [comment]
Fixed in version 1.0.5 (available [here ](https://mega.nz/#!9JN2xZpb!iiE2rSWTss0yoB7hLEbZ4xFUirEfI_q_wkOvyVarFgY)for the moment since i've changed my pgp key on Ore and i must wait 3 days before uploading a new version)
