### ISSUE TITLE
CRASH REPORT - 1.11.2 Minecraft Forge - Spongeforge-1.11.2-2393-6.1.0-BETA-2448.jar

### ISSUE THREAD

**Issue by HalestormXV** [JimiIT92/UniverseGuard#7]
Your plugin seems to randomly crash the server. I have been unable to decipher a cause but I do know it is directly related to UniverseGuard in parsing the CrashLog. 

Here is the CrashLog: https://pastebin.com/Wb0gwk3U

And here is what I gather to possibly be related to something in here:
https://github.com/JimiIT92/UniverseGuard/blob/master/src/main/java/com/universeguard/region/Region.java

Unfortunatly this is a rather serious issue that I hope can be resolved.

**Comment by JimiIT92** [comment]
It looks like you are using the 1.0 version, wich is an older one. Try using the latest version, wich can be found on the Sponge Ore page linked in the wiki or can be downloaded here
https://mega.nz/#!9JN2xZpb!iiE2rSWTss0yoB7hLEbZ4xFUirEfI_q_wkOvyVarFgY

**Comment by HalestormXV** [comment]
Same issue on 1.0.5 version: https://pastebin.com/ARWr3kk6

**Comment by JimiIT92** [comment]
Ok, will look into it and fix it as soon as possible
